### ISSUE TITLE
Implementing MTLS/SSL

### ISSUE THREAD

**Issue by lsglucas** [HoneyryderChuck/httpx#35] opened 2024-02-11 01:36 UTC
Hey!

I have a server which needs to be called using MTLS/SSL. 

I tried doing the following:

```ruby
http = HTTPX.with(
  ssl: {
    verify: true,
    verify_mode: OpenSSL::SSL::VERIFY_PEER,
    client_cert: OpenSSL::X509::Certificate.new(cert),
    client_key: OpenSSL::PKey::RSA.new(key)
  }
).get(url)
```

But it does not work, the application just hangs. The only log I get is the following:

```sh
resolver: answer AAAA url.com.br: [#<IPAddr>, #<IPAddr>]
```

Am I doing anything wrong? Does HTTPX supports SSL in the same way as Faraday?

This is the Faraday code I use and it is currently working:

```ruby
connection = Faraday.new(url: base_url, ssl: {
  verify: true,
  verify_mode: OpenSSL::SSL::VERIFY_PEER,
  client_cert: OpenSSL::X509::Certificate.new(cert),
  client_key: OpenSSL::PKey::RSA.new(key)
}
) do |faraday|
  faraday.request :json
end

connection.get(url)
```

**Comment by HoneyryderChuck** [comment] 2024-02-11 22:57
Hi, 

httpx supports the same options as OpenSSL::SSL::SSLContext#set_params, in the ssl option, so you can use the docs as reference (https://docs.ruby-lang.org/en/master/OpenSSL/SSL/SSLContext.html#method-i-set_params)

**Comment by lsglucas** [comment] 2024-02-12 12:15
Thanks for the quick reply, and for the clarification!

I was using the wrong name on the params, I managed to make it work with the following:

```ruby
http = HTTPX.with(
  ssl: {
    verify_mode: OpenSSL::SSL::VERIFY_PEER,
    cert: OpenSSL::X509::Certificate.new(cert),
    key: OpenSSL::PKey::RSA.new(key)
  }
).get(url)
```

**Comment by HoneyryderChuck** [comment] 2024-02-12 14:14
Great that worked. I'll keep this open though, as I'll address the hanging part when I find the time.

**Comment by HoneyryderChuck** [comment] 2024-02-27 12:33
can't reproduce the hanging behaviour, wrongly outlied ssl options will result in a NoMethodError, as expected. closing until further reproduction.

**Closed by HoneyryderChuck** 2024-02-27 12:33 UTC
