### ISSUE TITLE
HTTP/2 multiplexing with Brotli encoding

### ISSUE THREAD

**Issue by Aubermean** [HoneyryderChuck/httpx#28] opened 2023-12-08 13:10 UTC
It doesn't seem to work! I get `<HTTP2Next::Error::ProtocolError: Needs more input>` I have to disable br and the brotli plugin, then HTTP/2 multiplexing works perfectly. Now I have found a server that supports it, it's incredible to see by the way... hats off to you again for this library!

`/Users/user/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/httpx-1.1.5/lib/httpx/response/body.rb:192:in `inflate': Needs more input (Brotli::Error)`

**Comment by HoneyryderChuck** [comment] 2023-12-15 17:05
tried to reproduce this with some websites serving brotli, couldn't reproduce it. Closing until further reproduction.

**Closed by HoneyryderChuck** 2023-12-15 17:05 UTC
