### ISSUE TITLE
Slow file downloads with HTTP2

### ISSUE THREAD

**Issue by Aubermean** [HoneyryderChuck/httpx#32] opened 2023-12-25 14:55 UTC
Hi, here's a reproducible bugreport this time :)

If server supports HTTP2, then downloading a file takes forever!

```
require 'benchmark'
require 'httpx'
require 'typhoeus'
require 'net/http'
require 'uri'

http1_url = "http://ipv4.download.thinkbroadband.com/20MB.zip"
http2_url = "https://www2.census.gov/topics/genealogy/2010surnames/names.zip" # ~13MB

result = Benchmark.bm do |x|
  x.report("HTTPX.get HTTP1:") { HTTPX.get(http1_url) }
  x.report("HTTPX.get HTTP2:") { HTTPX.get(http2_url) }
  x.report("Net::HTTP.get HTTP1:") { Net::HTTP.get(URI(http1_url)) }
  x.report("Net::HTTP.get HTTP2:") { Net::HTTP.get(URI(http2_url)) }
  x.report("Typhoeus.get HTTP1:") { Typhoeus.get(http1_url) }
  x.report("Typhoeus.get HTTP2:") { Typhoeus.get(http2_url) }
end

result.each do |r|
  puts "#{r.label} #{r.real} seconds"
end

HTTPX.get HTTP1: 1.1476320000365376 seconds
HTTPX.get HTTP2: 47.604976000031456 seconds
Net::HTTP.get HTTP1: 2.000872999895364 seconds
Net::HTTP.get HTTP2: 1.9986679998692125 seconds
Typhoeus.get HTTP1: 0.14470500010065734 seconds
Typhoeus.get HTTP2: 0.6453960000071675 seconds

```

**Comment by HoneyryderChuck** [comment] 2023-12-25 18:13
Thx for the report @Aubermean I'll have a look during the week.

**Comment by HoneyryderChuck** [comment] 2023-12-27 17:48
I can confirm i can reproduce the issue.

The overhead comes from the socket jumping from `wait_readable`, but then calling `read_nonblock` and getting `:wait_readable` again, which creates a busy loop which hijacks the whole execution.

The problem seems to be specifically with `SSLSocket#wait_readable` (at least the TCPSocket identifies bytes to read from the buffer). My guess is that there was some recent change to the `sysread` call...

**Comment by HoneyryderChuck** [comment] 2024-01-03 14:15
I narrowed this down to issues of that particular peer server when setting up downloads using the standard HTTP/2 default settings.

The same delays can for example be reproduced using `nghttp`, which uses the same defaults as `httpx`. The server seems to, in the face of it, send a lot of incomplete TLS records, which wakeup the loop constantly without any action beyond waiting for more data. 

The same does not happen with `curl`, which uses `nghttp2` under the hood, but [uses different](https://github.com/curl/curl/blob/eeda18b1d2511cb9716066e5b29d81556a4f1355/lib/http2.c#L72) [HTTP/2 connection settings](https://github.com/bch/curl/commit/8347da54f42e6d4e793aa9fd6db59b86d4b3ccba), which have been deemed, over time, more suitable for the "transfer data" case which is curl main bread and butter.

As a workaround to achieve better throughput, you can use therefore:

```ruby
HTTPX.get(http2_url, http2_settings: {settings_initial_window_size: 10 * 1024 * 1024})
```

Further settings tweaks may be required to achieve comparable (to curl) throughput though.

I'm going to close this, as it's not a library issue, but I'd be ok if you would open a discussion about using other defaults for HTTP/2 settings, in order to start gathering community feedback.

**Closed by HoneyryderChuck** 2024-01-03 14:15 UTC
