### ISSUE TITLE
Multiple urls hangs

### ISSUE THREAD

**Issue by fagci** [HoneyryderChuck/httpx#5] opened 2022-07-07 08:16 UTC
Sometimes I get hanged ruby process when using multiple urls get request.

Using this way:

```ruby
responses = [*HTTPX.with(debug: STDERR, debug_level: 2).with(timeout: timeout_options).get(*urls)].to_a
```

Timings not helps here:

```ruby
timeout_options = {
  operation_timeout: 25,
  connect_timeout: 3,
  keep_alive_timeout: 15,
  total_timeout: 30
}
```

`negotiated -> closed` appears, but results not yelded.

When I press Ctrl-C, I got:

```
^C: frame was sent!
: {:type=>:goaway, :last_stream=>27, :error=>:no_error, :payload=>nil}
: frame was sent!
: {:type=>:goaway, :last_stream=>5, :error=>:no_error, :payload=>nil}
: frame was sent!
: {:type=>:goaway, :last_stream=>1, :error=>:no_error, :payload=>nil}
: frame was sent!
: {:type=>:goaway, :last_stream=>1, :error=>:no_error, :payload=>nil}
Traceback (most recent call last):
        16: from /home/user/tools/site-monitor.rb:28:in `<main>'
        15: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/chainable.rb:8:in `get'
        14: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/session.rb:36:in `request'
        13: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/session.rb:186:in `send_requests'
        12: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/session.rb:210:in `receive_requests'
        11: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/session.rb:210:in `loop'
        10: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/session.rb:215:in `block in receive_requests'
         9: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/session.rb:215:in `catch'
         8: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/session.rb:215:in `block (2 levels) in receive_requests'
         7: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/pool.rb:28:in `next_tick'
         6: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/pool.rb:28:in `catch'
         5: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/pool.rb:36:in `block in next_tick'
         4: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/selector.rb:134:in `select'
         3: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/selector.rb:115:in `select_one'
         2: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/resolver/native.rb:122:in `raise_timeout_error'
         1: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/resolver/native.rb:154:in `do_retry'
/var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/resolver/native.rb:154:in `negative?': Interrupt
```

**Comment by fagci** [comment] 2022-07-07 08:28
When i down debug_level to 1, once I got hangs on:

```
resolver: server: udp://8.8.8.8:53...
WRITE: 39 bytes...
```
Timeout not works here too.

**Comment by HoneyryderChuck** [comment] 2022-07-07 10:47
hi @fagci , thx for the report.

Can you provide the full backtrace when using debug level to 2, pointing also at which point the hang happens? Either that, or a script reproducing the issue, would be great to get started.

**Comment by HoneyryderChuck** [comment] 2022-07-07 16:47
I didn't receive any email. However, can you post it here? if too much text, feel free to use https://gist.github.com/ , and don't forget to remove any confidential information that may be exposed in the logs.

**Comment by HoneyryderChuck** [comment] 2022-07-08 10:02
Here's what I can analyze from those logs:

20 requests were performed from 4 different domains:
- 3 on xxx.ru (HTTP/2, all streams closed, connection didn't close)
- 14 on www.xxx.ru (HTTP/2, all streams closed, connection didn't close)
- 1 on shop.xxx.ru (HTTP/2, all streams closed, connection didn't close)
- 2 on (another) xxx.ru (HTTP/1.1 pipeline, connection closed after last request)

I'm assuming your script hung before the last 3 "negotiated -> closed" log lines.

The fact that the connections didn't close may indicate that there were issues in the session closing routine.

Could you post a snippet of how you're using httpx to perform this flow? Feel free to obfuscate the URLs, I'm most interested on how the code is called, and also if you're using any plugin.

**Comment by fagci** [comment] 2022-07-08 10:16
```ruby
  timeout_options = {
    operation_timeout: 25,
    connect_timeout: 3,
    keep_alive_timeout: 15,
    total_timeout: 30
  }

  session = HTTPX
            .plugin(:rate_limiter)
            .with(debug: $stderr, debug_level: 2)
            .with(timeout: timeout_options)

  responses = [*session.get(*urls)].to
```

**Comment by HoneyryderChuck** [comment] 2022-07-08 11:38
Looking back at your logs, I see smth spotty with the DNS queries.

* I see 6 instances of `resolver: query A`, which are essentially 6 DNS requests;
* I see 4 instances of `resolver: answer `, which are 4 DNS responses;

Also, isolating the DNS logs:

```
resolver: query A for www.xxx.ru
resolver: server: udp://xxx.xxx.xxx.xxx:53...
WRITE: 39 bytes...
resolver: query A for xxx.ru
WRITE: 35 bytes...
resolver: answer www.xxx.ru: [#<IPAddr: IPv4:xxx.xxx.xxx.xxx/xxx.xxx.xxx.xxx>]
resolver: query A for xxx.ru
WRITE: 34 bytes...
 idle -> idle
Connected to xxx.xxx.xxx.xxx (#7) # first xxx.ru
...
resolver: answer xxx.ru: [#<IPAddr: IPv4:xxx.xxx.xxx.xxx/xxx.xxx.xxx.xxx>]
resolver: query A for xxx.ru
WRITE: 36 bytes...
 idle -> idle
Connected to xxx.xxx.xxx.xxx (#8) # second xxx.ru
....
resolver: answer xxx.ru: [#<IPAddr: IPv4:xxx.xxx.xxx.xxx/xxx.xxx.xxx.xxx>]
resolver: query A for shop.xxx.ru
WRITE: 41 bytes...
 idle -> idle
Connected to xxx.xxx.xxx.xxx (#10) # third xxx.ru
...
resolver: answer shop.xxx.ru: [#<IPAddr: IPv4:xxx.xxx.xxx.xxx/xxx.xxx.xxx.xxx>]
resolver: query A for xxx.ru
WRITE: 56 bytes...
 idle -> idle
Connected to xxx.xxx.xxx.xxx (#11) # shop.xxx.ru
...
```

So, there is no corresponding connection to the third "xxx.ru" (it's a bit hard to track the names without uniquely describing the domains :) ).

So I believe that your script is querying more than 4 domains, it's just that 4 of them resolved, and somehow the 5th request is stuck on DNS resolution. Based on your top-level report, and this log when you interrupted the script:

```
: {:type=>:goaway, :last_stream=>1, :error=>:no_error, :payload=>nil}
Traceback (most recent call last):
        16: from /home/user/tools/site-monitor.rb:28:in `<main>'
        15: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/chainable.rb:8:in `get'
        14: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/session.rb:36:in `request'
        13: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/session.rb:186:in `send_requests'
        12: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/session.rb:210:in `receive_requests'
        11: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/session.rb:210:in `loop'
        10: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/session.rb:215:in `block in receive_requests'
         9: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/session.rb:215:in `catch'
         8: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/session.rb:215:in `block (2 levels) in receive_requests'
         7: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/pool.rb:28:in `next_tick'
         6: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/pool.rb:28:in `catch'
         5: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/pool.rb:36:in `block in next_tick'
         4: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/selector.rb:134:in `select'
         3: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/selector.rb:115:in `select_one'
         2: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/resolver/native.rb:122:in `raise_timeout_error'
         1: from /var/lib/gems/2.7.0/gems/httpx-0.20.3/lib/httpx/resolver/native.rb:154:in `do_retry'
```

it shows that it gets stuck on the timeout-now-retry process of the DNS native resolver.

**Comment by fagci** [comment] 2022-07-08 12:06
Yes, those accessible publicy, coz of script tries to get statuses from each of them, and successfully, but sometimes stuck. Maybe that is "rate limiting" by 8.8.8.8 (was main resolver at time of trace)

**Comment by HoneyryderChuck** [comment] 2022-07-08 12:44
it's definitely not rate-limiting. can you share the domains, and potentially the urls, if it's not a secret?

**Comment by HoneyryderChuck** [comment] 2022-07-12 10:25
@fagci friendly ping, so that this isn't forgotten.

**Comment by HoneyryderChuck** [comment] 2022-07-21 16:30
Closing due to inactivity. Feel free to report with more feedback I can use to debug, happy to reopen

**Closed by HoneyryderChuck** 2022-07-21 16:30 UTC

**Comment by HoneyryderChuck** [comment] 2022-07-29 16:55
FYI https://gitlab.com/honeyryderchuck/httpx/-/merge_requests/215 (if you want to give it a try).
